# Server settings are defined here.
# See "~/CurryMUD/res/help/admin/topics/settings" for more info.

# Enable debug commands?
debug: true

# Start the EKG server? (Effective only when "debug" is also true.)
ekg: true

# Enable logging?
log: true

# Start the REST service?
rest: true

# Enable the back door? (Effective only when "debug" is also true.)
zBackDoor: true