# Server settings are defined here.

# Enable debug commands?
debug: true

# Start the EKG server? (Effective only when "debug" is also true.)
ekg: true

# Enable logging?
log: true

# Start the REST service?
rest: true

# Enable the back door? (Effective only when "debug" is also true.)
zBackDoor: true